import type { CoachState } from '../types'
import { EMPTY_CARD } from './card'
import { DEFAULT_SETTINGS } from './config'

export const INITIAL: CoachState = {
  ready: false,
  prefs: {
    enabled: true,
    sessions: 0,
    hintTaps: 0,
    settings: DEFAULT_SETTINGS,
    fade: {},
    dismissals: {},
    silenced: [],
  },
  station: 'plan',
  focus: null,
  stationReason: '',
  pulse: false,
  card: EMPTY_CARD,
  band: null,
  bandLoading: false,
  notes: {},
  pendingSuggest: null,
  shownSuggest: null,
  ownCheck: null,
  menuOpen: false,
  pickerOpen: false,
  settingsOpen: false,
  meta: [],
  metaBusy: false,
  metaContext: '',
  turnIndex: 0,
  cost: { tokens: 0, usd: 0 },
  lastPrompt: '',
  lastAnswer: '',
  fresh: [],
  tools: [],
  dividerTurn: -1,
  lastBandTurn: 0,
  sessionDismissals: {},
  silencedSession: [],
  ignoredGaps: {},
  askedPause: false,
  sessionCounted: false,
  pushPass: false,
  lastFill: '',
  usage: { convUsd: null, isApprox: true },
  bandRow: '',
  latestNote: null,
  rows: { user: '', reply: '', userTurn: 0, replyTurn: 0 },
}
